#!/usr/bin/env bash


source "$TARGET_USER/git/vault_run/vault_run_install/lib/installer"
function log()
{
    local msg=$1
    local timestamp=$(date +"%T")
    local funcName=${FUNCNAME[*]}
    echo "[VAULT]:[$timestamp]:[$funcName]:$msg"
}



function encrypt() {
  openssl aes-256-cbc -a -salt -in $filename -out $filename.enc >2&>1 /dev/null
  retVal=$?
  if [ $retVal -eq 0 ]; then
    rm $filename
    echo "encrypted file successfully"
  fi

}

function decrypt() {
  local file=$1
  openssl aes-256-cbc -d -a -in .$filename -out $filename >2&>1 /dev/null
  rm $file

}

function sealVault()
{
    log "in seal function"
    encrypt

}

function unsealVault()
{
    log "in seal function"
}