#!/usr/bin/env bash


source "$TARGET_USER/git/vault_run/vault_run_install/lib/file_handler"
# Save vault to file
function createVault() {
  # check if vault path exist
if [[ -f "$filename" ]]; then
    echo "You cant create $filename is alredy exist you need to run with diffrent user "
    exit 1

echo "vault will be created onto $VAULT_PATH"
fi
for key in "${keys[@]}"
do
   echo $key >>$filename
done
sed -i "/^timestamp=/s/=.*/=$(date +%s)/" $filename
sed -i "/^owner=/s/=.*/=$owner/" $filename
}


# function genKey() {
#   # True if FILE exist
#   local key=${1-}
#   if [ -f $keyFile ]; then
#     echo "Keyfile:: $VAULT_K
#     #echo "Generate keyfile: $VAULT_KEYS"
#     arr["key"]=openssl rand -hex 8
#     echo arr["key"] >$keyFile
#   fi
# }
