#!/usr/bin/env bash


# Save vault to file
function createVault() {
  local output=""
  output="#vault_runner:${VAULT_VERSION}"
  if [ -f $VaultFile ]; then
    echo "Vaultfile:: $VaultFile already exists"
    exit 1
  else
    #echo "Generate Vaultfile $VaultFile"
    touch $VaultFile
    echo $output >>$VaultFile
  fi
}

function genKey() {
  # True if FILE exist
  local key=${1-}
  if [ -f $keyFile ]; then
    echo "Keyfile:: $VAULT_KEYS already exists"
    exit 1
  else
    #echo "Generate keyfile: $VAULT_KEYS"
    arr["key"]=openssl rand -hex 8
    echo arr["key"] >$keyFile
  fi
}

function encrypt() {
  #gpg -c $keyFile
  openssl aes-256-cbc -a -salt -in $keyFile -out $keyFile.enc
  retVal=$?
  if [ $retVal -eq 0 ]; then
    rm $keyFile
    echo "encrypted file sucessfully"
  fi

}

function decrypt() {
  local file=$1
  openssl aes-256-cbc -d -a -in .$file -out $file >2&>1
  rm $file

}
