#!/usr/bin/env bash


source "vars"

function createVault() {
  # check if vault path exist
if [[ -f "$FILE_NAME" ]]; then
    echo "You cant create $FILE_NAME is alredy exist you need to run with diffrent user "
    exit 1

echo "vault will be created onto $USER_DATA"
fi
for key in "${keys[@]}"
do
   echo $key >>$FILE_NAME
done
sed -i "/^timestamp=/s/=.*/=$(date +%s)/" $FILE_NAME
sed -i "/^OWNER=/s/=.*/=$OWNER/" $FILE_NAME
}


# function genKey() {
#   # True if FILE exist
#   local key=${1-}
#   if [ -f $keyFile ]; then
#     echo "Keyfile:: $VAULT_K
#     #echo "Generate keyfile: $VAULT_KEYS"
#     arr["key"]=openssl rand -hex 8
#     echo arr["key"] >$keyFile
#   fi
# }
